apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fps-spring-service
  annotations:
    dev.azure.com/host-org: dev.azure.com/TechM-FPS
    dev.azure.com/project-repo: FPS-Spring-Pipeline/FPS-Spring-Pipeline
spec:
  type: service
  owner: user:default/guest
  lifecycle: experimental